<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

/**
 * 
 * @author Pubudu Nawarathna <pubudumanoj@gmail.com>
 * @category Booking
 * @since File available since Release 1.0.0
 * @access public
 * 
 */
class Print_voucher_control extends CI_Controller {

    /**
     * @access private
     * Use to verfiy user is logged in or not.
     */
    private $logged_in;

    /**
     * @access private
     * store detail reviewer
     * this is only send to database if an admin insert the details
     * 
     */
    private $role = null;

    function __construct() {
        /*
         * Short description: call super class constructor.
         * 
         */
        parent::__construct();
        /*
         * When user is logging in to system
         * SESSIONS are declared.
         * from anywhere these sessions can access using
         * $this->session->userdata('SESSION_NAME');
         * If user is logged in @varibale $logged_in set to True
         * otherwise it is set to False.
         * 
         */
        $this->load->model('booking/booking_model');
        $this->load->helper('pdf_helper');
        if ($this->session->userdata('logged_in')) {
            $this->logged_in = TRUE;
            $this->role = $this->session->userdata('role');
        } else {
            $this->logged_in = FALSE;
        }
    }

    public function validate_information() {
        $this->load->library('form_validation');
        $this->form_validation->set_rules('patient_contact_no', 'Contact No of the Patient', 'trim|required|xss_clean');
        $this->form_validation->set_rules('patient_name', 'Patient Name', 'trim|required|xss_clean');
        if ($this->form_validation->run() == FALSE) {


            $this->load_view();
        } else {

            $this->print_voucher();
        }
    }

    public function print_voucher() {
        $physician = $this->input->post('physician');
        $physician_name = $this->input->post('physician_name');
        $center_name = $bname = $this->input->post('center_name');
        $region = $bname = $this->input->post('region');
        $start_time = $bname = $this->input->post('start_time');
        $number = $bname = $this->input->post('number');
        $booking_date = $bname = $this->input->post('booking_date');
        $patient_name = $this->input->post('patient_name');
        $patient_contact_no = $bname = $this->input->post('patient_contact_no');
        $dbRet = $this->add_booking($patient_name, $patient_contact_no, $booking_date, $number, $physician);
        if ($dbRet) {
            ob_start();
            tcpdf();
            $pdf = new TCPDF('L', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
            $title = 'Booking Voucher';
            $pdf->SetTitle($title);
            $pdf->SetCreator(PDF_CREATOR);
            $pdf->SetHeaderMargin(30);
            $pdf->SetTopMargin(20);
            $pdf->setFooterMargin(20);
            $pdf->SetAutoPageBreak(true);
            $pdf->SetAuthor('Author');
            $pdf->SetDisplayMode('real', 'default');
            $pdf->SetHeaderData(PDF_HEADER_LOGO, 50, $title, PDF_HEADER_STRING);
            $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
            $pdf->Footer("Automatically generated by \"Suwoda\" Ayurvedic Medical Information System at");
            $pdf->setFooterFont("helvetica");
            $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
            $pdf->SetDefaultMonospacedFont('helvetica');
            $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
            $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
            $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
            $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
            $pdf->SetFont('helvetica', '', 12);
            $pdf->setFontSubsetting(false);
            $pdf->AddPage();
            echo "<p>Physician Name: " . $physician_name . "</p>";
            echo "<p>Medical Centre: " . $center_name . "</p>";
            echo "<p>Nearest City: " . $region . "</p>";
            echo "<p>Treatment Start Time: " . $start_time . "</p>";
            echo "<p>Booking Number: " . $number . "</p>";
            echo "<p>Booking Date: " . $booking_date . "</p>";
            echo "<p>Patient Name: " . $patient_name . "</p>";
            $pdf->Line(15, 113, 195, 113);
            echo "<p>Contact No of the Patient: " . $patient_contact_no . "</p>";
            echo "<p></p>";
            echo "<p style=\"font-size:8px\">Automatically generated by \"Suwoda\" Ayurvedic Medical Center at " . date('Y-m-d H:i:s') . "</p>";


            $content = ob_get_contents();
            ob_end_clean();
            $pdf->writeHTML($content, true, false, true, false, '');
            $pdf->Output('voucher.pdf', 'I');
        } else {
            ?>
            <script>
                alert("Patient Name and Telephone Number already exist");
            </script>
            <?php

            $this->load_view();
        }
    }

    public function add_booking($patient_name, $patient_contact_no, $booking_date, $number, $physician) {
      return  $this->booking_model->add_booking($patient_name, $patient_contact_no, $booking_date, $number, $physician);
    }

    public function load_view() {

        $data['title'] = ucfirst('Setup Booking Schedule');

        $data['physician_mail'] = $this->session->userdata('email');
        $data['role'] = $this->session->userdata('role');
        $data['lname'] = $this->session->userdata('lname');
        $data['logged_in'] = $this->logged_in;
        $this->load->view('templates/header', $data);
        $this->load->view('medical/physician', $data);
        $this->load->view('templates/footer', $data);
    }

}
?>