<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

/**
 * 
 * Short Description: class Disease_control- Controll functions in medical information reslut showing
 * 
 * Long Description:
 * Show the view file information when call the class.
 * Send search data to Information model class.
 * link with view Information and model Information model
 * 
 * @author Pubudu Nawarathna <pubudumanoj@gmail.com>
 * @category Information
 * @since File available since Release 1.0.0
 * @access public
 * 
 */
class Plant_pdf_control extends CI_Controller {

    /**
     * @access private
     * Use to verfiy user is logged in or not.
     */
    private $logged_in;

    function __construct() {

        parent::__construct();
        $this->load->model('reports/Disease_pdf_model');
        $this->load->helper('pdf_helper');
        /*
         * create a variable logged_in with value true if the user is logged in
         */
        if ($this->session->userdata('logged_in')) {
            $this->logged_in = TRUE;
        } else {
            $this->logged_in = FALSE;
        }
    }

    public function index() {

        /*
         * default main method
         * call when normally request the class
         * initialize all the varaibles to default values
         */
    }

    function count_all_plants() {
        /*
         * count the all diseases for all the years
         */
        return $this->Disease_pdf_model->count_all_plants();
    }

    function plants_by_month($year) {
        /*
         * count diseases for each month in a given year
         */

        return $this->Disease_pdf_model->disease_by_month($year);
    }

    function disease_cat_by_year($year) {
        /*
         * count diseases for each categoary in a given year
         */

        return $this->Disease_pdf_model->disease_cat_by_year($year);
    }

    function disease_by_range($date1, $date2) {
        /*
         * count the diseases for each category for given date range
         */

        return $this->Disease_pdf_model->disease_by_range($date1, $date2);
    }

    public function generate_disease_reports() {


        ob_start();
        tcpdf();
        $pdf = new TCPDF('L', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        $title = 'Disease Statistics';
        $pdf->SetTitle($title);
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetHeaderMargin(30);
        $pdf->SetTopMargin(20);
        $pdf->setFooterMargin(50);
        $pdf->SetAutoPageBreak(true);
        $pdf->SetAuthor('Author');
        $pdf->SetDisplayMode('real', 'default');
        $pdf->SetHeaderData(PDF_HEADER_LOGO, 50, $title, PDF_HEADER_STRING);
        $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
        $pdf->Footer("Suwoda Medicals");
        $pdf->setFooterFont("helvetica");
        $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
        $pdf->SetDefaultMonospacedFont('helvetica');
        $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
        $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
        $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
        $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
        $pdf->SetFont('helvetica', '', 12);
        $pdf->setFontSubsetting(false);
        $pdf->SetPrintFooter(TRUE);
        $pdf->AddPage();
        echo "<p style=\"font-size:8px\">Automatically generated by \"Suwoda\" Ayurvedic Medical Information system on " . date('Y-m-d H:i:s') . "</p>";

        if ($this->input->post('total_disease_count')) {

            $all_count = $this->count_all_disease();
            ?>

            <h4>Total Diseases count by year</h4>
            <table style="margin:2px;padding:5px;
                   width:50%;
                   box-shadow: 10px 10px 5px #888888;
                   border:1px solid #3f7f00;

                   ">
                <tr >
                    <td style="background-color:#d4ffaa; border-bottom: 0.5px solid #3f7f00; border-right: 0.5px solid #3f7f00">
                        Year
                    </td>
                    <td style="background-color:#d4ffaa; border-bottom: 0.5px solid #3f7f00; border-right: 0.5px solid #3f7f00" >
                        Inserted Diseases Count
                    </td>
                </tr>

                        <?php foreach ($all_count as $row) { ?>
                    <tr>

                        <td style="border-bottom: 1px solid #3f7f00;border-right: 1px solid #3f7f00">
                            <?php
                            echo $row->year;
                            ?>
                        </td>
                        <td style="border-bottom: 1px solid #3f7f00">
                    <?php
                    echo $row->count;
                    ?></td>

                    </tr>
            <?php } ?>

            </table>

            <?php
        }
        if ($this->input->post('disease_by_month')) {

            $year = $this->input->post('disease_by_month_year');
            $month_count = $this->disease_by_month($year);
            ?>

            <h4>Diseases count by month for year <?php echo $year ?></h4>
            <table style="margin:2px;padding:5px;
                   width:50%;
                   box-shadow: 10px 10px 5px #888888;
                   border:1px solid #3f7f00;

                   ">
                <tr >
                    <td style="background-color:#d4ffaa; border-bottom: 0.5px solid #3f7f00; border-right: 0.5px solid #3f7f00">
                        Month
                    </td>
                    <td style="background-color:#d4ffaa; border-bottom: 0.5px solid #3f7f00; border-right: 0.5px solid #3f7f00" >
                        Inserted Diseases Count
                    </td>
                </tr>

                        <?php $total = 0;
                        foreach ($month_count as $row) { ?>
                    <tr>

                        <td style="border-bottom: 1px solid #3f7f00;border-right: 1px solid #3f7f00">
                            <?php
                            echo $row->month;
                            ?>
                        </td>
                        <td style="border-bottom: 1px solid #3f7f00">
                <?php
                $total = $total + $row->count;
                echo $row->count;
                ?></td>

                    </tr>
                        <?php } ?>
                <tr>
                    <td style="background-color:#3f7f00; ">Total</td>
                    <td><?php
            echo $total;
            ?></td>
                </tr>

            </table>

            <?php
        }
        ////////////////

        if ($this->input->post('disease_by_year')) {

            $year = $this->input->post('disease_cat_by_year');
            $cat_count = $this->disease_cat_by_year($year);
            ?>

            <h4>Diseases count by category for year <?php echo $year ?></h4>
            <table style="margin:2px;padding:5px;
                   width:50%;
                   box-shadow: 10px 10px 5px #888888;
                   border:1px solid #3f7f00;

                   ">
                <tr >
                    <td style="background-color:#d4ffaa; border-bottom: 0.5px solid #3f7f00; border-right: 0.5px solid #3f7f00">
                        Disease Category
                    </td>
                    <td style="background-color:#d4ffaa; border-bottom: 0.5px solid #3f7f00; border-right: 0.5px solid #3f7f00" >
                        Inserted Diseases Count
                    </td>
                </tr>

                        <?php $total = 0;
                        foreach ($cat_count as $row) {
                            ?>
                    <tr>

                        <td style="border-bottom: 1px solid #3f7f00;border-right: 1px solid #3f7f00">
                            <?php
                            echo $row->category;
                            ?>
                        </td>
                        <td style="border-bottom: 1px solid #3f7f00">
                    <?php
                    $total = $total + $row->count;
                    echo $row->count;
                    ?></td>

                    </tr>
                        <?php } ?>
                <tr>
                    <td style="background-color:#3f7f00; ">Total</td>
                    <td><?php
            echo $total;
            ?></td>
                </tr>
            </table>

            <?php
        }
        ///////

        if ($this->input->post('disease_by_range')) {

            $date1 = $this->input->post('disease_by_range_date1');
            $date2 = $this->input->post('disease_by_range_date2');
            $cat_count_range = $this->disease_by_range($date1, $date2);
            ?>

            <h4>Diseases count by category from <?php echo $date1 ?> to <?php echo $date2 ?> </h4>
            <table style="margin:2px;padding:5px;
                   width:50%;
                   box-shadow: 10px 10px 5px #888888;
                   border:1px solid #3f7f00;

                   ">
                <tr >
                    <td style="background-color:#d4ffaa; border-bottom: 0.5px solid #3f7f00; border-right: 0.5px solid #3f7f00">
                        Disease Category
                    </td>
                    <td style="background-color:#d4ffaa; border-bottom: 0.5px solid #3f7f00; border-right: 0.5px solid #3f7f00" >
                        Inserted Diseases Count
                    </td>
                </tr>

                        <?php  $total =0;
                        foreach ($cat_count_range as $row) { ?>
                    <tr>

                        <td style="border-bottom: 1px solid #3f7f00;border-right: 1px solid #3f7f00">
                            <?php
                            echo $row->category;
                            ?>
                        </td>
                        <td style="border-bottom: 1px solid #3f7f00">
                    <?php
                     $total = $total + $row->count;
                    echo $row->count;
                    ?></td>

                    </tr>
                        <?php } ?>
                <tr>
                    <td style="background-color:#3f7f00; ">Total</td>
                    <td><?php
            echo $total;
            ?></td>
                </tr>
            </table>

            <?php
        }
        /////
        $content = ob_get_contents();
        ob_end_clean();
        $pdf->writeHTML($content, true, false, true, false, '');
        $pdf->Output('disease_stats.pdf', 'I');
    }

}
?>
